# SPDX-License-Identifier: AGPL-3.0-only
# Copyright 2026-present the Zopedia team. All rights reserved. See /studio/LICENSE.AGPL-3.0

"""PostgreSQL database connectivity for Zopedia SQL tool support.

Uses asyncpg for non-blocking PostgreSQL access. All queries are executed
in read-only mode with statement-level timeouts and row limits.
"""

from __future__ import annotations

import json
import logging
import os
import re
from typing import Optional
from urllib.parse import unquote

import asyncpg

logger = logging.getLogger(__name__)

_pool: Optional[asyncpg.Pool] = None


async def create_pool(database_url: str) -> asyncpg.Pool:
    """Create and initialize an asyncpg connection pool.

    All connections are set to read-only by default as a defense-in-depth
    measure against non-SELECT queries generated by the LLM.
    """
    global _pool
    _pool = await asyncpg.create_pool(
        database_url,
        min_size=1,
        max_size=5,
        command_timeout=10,
        server_settings={
            "default_transaction_read_only": "on",
        },
    )
    logger.info("Database connection pool created (min=1, max=5, read-only)")
    return _pool


async def close_pool() -> None:
    """Close the connection pool gracefully."""
    global _pool
    if _pool:
        await _pool.close()
        _pool = None
        logger.info("Database connection pool closed.")


def pool_available() -> bool:
    """Return True if the connection pool is initialized and available."""
    return _pool is not None


# ── Table allowlist ──────────────────────────────────────────────────

def _get_allowed_tables() -> set[str] | None:
    """Return the set of allowed schema.table names, or None if unfiltered."""
    raw = os.getenv("ZOPEDIA_DB_ALLOWED_TABLES", "").strip()
    if not raw:
        return None
    allowed = set()
    for entry in raw.split(","):
        entry = entry.strip()
        if entry:
            allowed.add(entry)
    return allowed if allowed else None


def _table_in_allowlist(schema: str, table: str, allowlist: set[str] | None) -> bool:
    """Return True if the table is in the allowlist, or if no allowlist is set."""
    if allowlist is None:
        return True
    return f"{schema}.{table}" in allowlist


# ── Connection test ──────────────────────────────────────────────────

async def test_connection(
    host: str = "localhost",
    port: int = 5432,
    dbname: str = "",
    user: str = "",
    password: str = "",
) -> dict:
    """Test a database connection and return available tables.

    Creates a temporary connection — does NOT affect the main pool.
    Returns a dict with 'status' and either 'tables' / 'count' or 'detail' error.
    """
    import asyncpg

    try:
        conn = await asyncpg.connect(
            host=host,
            port=port,
            database=dbname,
            user=user,
            password=password,
            timeout=10,
        )
        try:
            # Validate connectivity
            await conn.execute("SELECT 1")

            # Fetch tables (same query as list_tables, but via temp conn)
            rows = await conn.fetch(
                """
                SELECT schemaname, tablename,
                       (SELECT reltuples::bigint
                        FROM pg_class
                        WHERE oid = (schemaname || '.' || tablename)::regclass) AS approx_rows
                FROM pg_tables
                WHERE schemaname NOT IN ('pg_catalog', 'information_schema')
                ORDER BY schemaname, tablename
                """
            )
            tables = [
                {
                    "schema": r["schemaname"],
                    "table": r["tablename"],
                    "approx_rows": r["approx_rows"] or 0,
                }
                for r in rows
            ]
            return {"status": "ok", "tables": tables, "count": len(tables)}
        finally:
            await conn.close()
    except asyncpg.exceptions.InvalidPasswordError:
        return {"status": "error", "detail": "Invalid password."}
    except asyncpg.exceptions.InvalidCatalogNameError:
        return {"status": "error", "detail": f"Database '{dbname}' does not exist."}
    except asyncpg.exceptions.ConnectionRejectedError as exc:
        return {"status": "error", "detail": f"Connection rejected: {exc}"}
    except Exception as exc:
        return {"status": "error", "detail": f"Connection failed: {exc}"}


# ── Table name validation ──────────────────────────────────────────

_TABLE_NAME_RE_IMPORT = None  # cached regex

def _validate_table_name(name: str) -> bool:
    """Reject table names with characters beyond alphanumeric + underscore + dash."""
    global _TABLE_NAME_RE_IMPORT
    if _TABLE_NAME_RE_IMPORT is None:
        import re
        _TABLE_NAME_RE_IMPORT = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_-]*$")
    return bool(_TABLE_NAME_RE_IMPORT.match(name))


# ── Schema introspection ───────────────────────────────────────────

async def list_tables() -> str:
    """Return a JSON list of all user tables and their approximate row counts."""
    if not _pool:
        return json.dumps({"error": "No database connection configured."})
    allowlist = _get_allowed_tables()
    try:
        async with _pool.acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT schemaname, tablename,
                       (SELECT reltuples::bigint
                        FROM pg_class
                        WHERE oid = (schemaname || '.' || tablename)::regclass) AS approx_rows
                FROM pg_tables
                WHERE schemaname NOT IN ('pg_catalog', 'information_schema')
                ORDER BY schemaname, tablename
                """
            )
            tables = [
                {
                    "schema": r["schemaname"],
                    "table": r["tablename"],
                    "approx_rows": r["approx_rows"] or 0,
                }
                for r in rows
                if _table_in_allowlist(r["schemaname"], r["tablename"], allowlist)
            ]
            return json.dumps({"tables": tables, "count": len(tables)}, default=str)
    except Exception as exc:
        logger.warning("Failed to list tables: %s", exc)
        return json.dumps({"error": f"Failed to list tables: {exc}"})


async def describe_table(table_name: str, schema: str = "public") -> str:
    """Return JSON describing a table's columns, types, and constraints.

    Uses parameterized queries to prevent SQL injection through table_name.
    """
    if not _pool:
        return json.dumps({"error": "No database connection configured."})

    if not _validate_table_name(table_name):
        return json.dumps({"error": f"Invalid table name: {table_name}"})

    allowlist = _get_allowed_tables()
    if not _table_in_allowlist(schema, table_name, allowlist):
        return json.dumps({"error": f"Table '{schema}.{table_name}' is not in the allowed tables list."})

    try:
        async with _pool.acquire() as conn:
            columns = await conn.fetch(
                """
                SELECT
                    c.column_name,
                    c.data_type,
                    c.is_nullable,
                    c.column_default,
                    c.character_maximum_length,
                    tc.constraint_type
                FROM information_schema.columns c
                LEFT JOIN information_schema.key_column_usage kcu
                    ON c.table_schema = kcu.table_schema
                    AND c.table_name = kcu.table_name
                    AND c.column_name = kcu.column_name
                LEFT JOIN information_schema.table_constraints tc
                    ON kcu.constraint_name = tc.constraint_name
                    AND tc.constraint_type IN ('PRIMARY KEY', 'FOREIGN KEY')
                WHERE c.table_schema = $1 AND c.table_name = $2
                ORDER BY c.ordinal_position
                """,
                schema,
                table_name,
            )

            if not columns:
                return json.dumps({"error": f"Table '{schema}.{table_name}' not found."})

            cols = []
            for r in columns:
                col = {
                    "name": r["column_name"],
                    "type": r["data_type"],
                    "nullable": r["is_nullable"] == "YES",
                    "max_length": r["character_maximum_length"],
                }
                if r["column_default"]:
                    col["default"] = r["column_default"]
                if r["constraint_type"]:
                    col["constraint"] = r["constraint_type"]
                cols.append(col)

            return json.dumps(
                {
                    "schema": schema,
                    "table": table_name,
                    "columns": cols,
                    "column_count": len(cols),
                },
                default=str,
            )
    except Exception as exc:
        logger.warning("Failed to describe table %s: %s", table_name, exc)
        return json.dumps({"error": f"Failed to describe table: {exc}"})


# ── Query execution ────────────────────────────────────────────────

# Keywords that are rejected even if the query starts with SELECT
_FORBIDDEN_KEYWORDS = [
    "insert ", "update ", "delete ", "drop ", "truncate ", "alter ",
    "create ", "grant ", "revoke ", "copy ", "vacuum", "reindex",
    "execute ", "call ",
]


async def execute_query(
    query: str,
    max_rows: int = 100,
    timeout_seconds: int = 10,
) -> str:
    """Execute a read-only SQL query with multiple safety layers.

    Returns JSON: {columns, rows, row_count, truncated} on success,
    or {error} on failure.
    """
    if not _pool:
        return json.dumps({"error": "No database connection configured."})

    clean = query.strip()
    if not clean:
        return json.dumps({"error": "Empty query."})

    # ── Safety: forbidden keywords ─────────────────────────────────
    clean_lower = clean.lower()
    for keyword in _FORBIDDEN_KEYWORDS:
        if clean_lower.startswith(keyword):
            return json.dumps(
                {"error": f"Only SELECT queries are allowed. Forbidden: {keyword.strip()}"}
            )
        # Check for keyword after semicolon (attempted multi-statement bypass)
        compact = clean_lower.replace(" ", "")
        if f";{keyword}" in compact:
            return json.dumps(
                {"error": f"Only SELECT queries are allowed. Forbidden: {keyword.strip()}"}
            )

    # ── Safety: must be SELECT or WITH ─────────────────────────────
    if not clean_lower.startswith("select ") and not clean_lower.startswith("with "):
        return json.dumps({"error": "Only SELECT (or WITH ... SELECT) queries are allowed."})

    # ── Safety: no multiple statements ─────────────────────────────
    if ";" in clean.rstrip(";"):
        return json.dumps({"error": "Multiple statements are not allowed."})

    # ── Auto-append LIMIT if absent ────────────────────────────────
    if "limit " not in clean_lower:
        clean = clean.rstrip(";").strip() + f" LIMIT {max_rows}"

    try:
        async with _pool.acquire() as conn:
            await conn.execute(f"SET LOCAL statement_timeout = '{timeout_seconds * 1000}'")
            await conn.execute("SET LOCAL default_transaction_read_only = on")

            records = await conn.fetch(clean)
            column_names = [k for k in records[0].keys()] if records else []
            rows = []
            for record in records:
                row = {}
                for col in column_names:
                    val = record[col]
                    if isinstance(val, (bytes, bytearray, memoryview)):
                        row[col] = f"<binary: {len(val)} bytes>"
                    elif hasattr(val, "isoformat"):
                        row[col] = val.isoformat()
                    elif isinstance(val, (int, float, str, bool, type(None))):
                        row[col] = val
                    else:
                        row[col] = str(val)
                rows.append(row)

            truncated = len(rows) >= max_rows
            return json.dumps(
                {
                    "columns": column_names,
                    "rows": rows,
                    "row_count": len(rows),
                    "truncated": truncated,
                },
                default=str,
            )
    except asyncpg.exceptions.QueryCanceledError:
        return json.dumps({"error": f"Query timed out after {timeout_seconds}s."})
    except Exception as exc:
        logger.warning("Query execution failed: %s", exc)
        return json.dumps({"error": f"Query failed: {exc}"})
